name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org
            binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=
            binary-caches-parallel-connections = 40
            sandbox = true
      - name: Download & Build 🔧
        run: |
          nix-build -j4 site.nix
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/
